export const SELECT_INSTANCE = 'SELECT_INSTANCE';
export const SET_INSTANCES = 'SET_INSTANCES';
export const RESET_MEMORY = 'RESET_MEMORY';
export const RESET_DISK = 'RESET_DISK';
export const SET_RESOURCE = 'SET_RESOURCE';
export const NEXT_INSTANCE = 'NEXT_INSTANCE';

export const TRAFFIC_GO = 'TRAFFIC_GO';
export const TRAFFIC_STOP = 'TRAFFIC_STOP';
export const TRAFFIC_DONE = 'TRAFFIC_DONE';
export const TRAFFIC_HIT = 'TRAFFIC_HIT';
export const TRAFFIC_STARTED = 'TRAFFIC_STARTED';
export const TRAFFIC_TOGGLE = 'TRAFFIC_TOGGLE';